# SPDX-License-Identifier: Apache-2.0
"""Generate a standalone Verilator build bundle for the OpenTSP AXI top.

This helper emits a minimal C++ simulation harness, a shell build script,
and metadata for building the FPGA-facing AXI top without cocotb.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import json


DEFAULT_TOP_MODULE = "opentsp_axi_top_sim"
DEFAULT_FILELIST = Path("fpga/generic_axi/filelist.f")
DEFAULT_OUTPUT_DIR = Path("artifacts/verilator_top")


@dataclass(frozen=True)
class VerilatorTopBuild:
    """Standalone Verilator top build description."""

    top_module: str
    filelist_path: Path
    output_dir: Path
    sources: tuple[Path, ...]
    main_cpp: Path
    build_script: Path
    metadata_json: Path

    @property
    def obj_dir(self) -> Path:
        return self.output_dir / "obj_dir"

    @property
    def binary_name(self) -> str:
        return self.top_module

    def verilator_command(self) -> list[str]:
        """Return the Verilator command used by the generated script."""

        return [
            "verilator",
            "-cc",
            "--exe",
            "--build",
            "--trace",
            "--timing",
            "--top-module",
            self.top_module,
            "--Mdir",
            self.obj_dir.as_posix(),
            "-o",
            self.binary_name,
            *[source.as_posix() for source in self.sources],
            self.main_cpp.as_posix(),
        ]


def read_filelist(path: str | Path) -> tuple[Path, ...]:
    """Read a simple Verilog/SystemVerilog filelist."""

    filelist_path = Path(path)
    sources: list[Path] = []

    for raw_line in filelist_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        sources.append(Path(line))

    return tuple(sources)


def generate_main_cpp(top_module: str) -> str:
    """Generate a minimal C++ harness for a Verilated top module."""

    header = f"V{top_module}.h"

    return f'''// SPDX-License-Identifier: Apache-2.0
// Auto-generated by OpenTSP Edge.
// Minimal standalone Verilator harness for {top_module}.

#include <stdint.h>
#include <stdio.h>

#include "verilated.h"
#include "verilated_vcd_c.h"
#include "{header}"

static void tick(V{top_module}* top, VerilatedVcdC* trace, uint64_t* time_ps) {{
    top->clk_i = 0;
    top->eval();
    if (trace) trace->dump(*time_ps);
    *time_ps += 5000;

    top->clk_i = 1;
    top->eval();
    if (trace) trace->dump(*time_ps);
    *time_ps += 5000;
}}

int main(int argc, char** argv) {{
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);

    V{top_module}* top = new V{top_module};
    VerilatedVcdC* trace = new VerilatedVcdC;

    top->trace(trace, 99);
    trace->open("opentsp_axi_top_sim.vcd");

    uint64_t time_ps = 0;

    top->rst_ni = 0;
    top->awaddr_i = 0;
    top->awvalid_i = 0;
    top->wdata_i = 0;
    top->wvalid_i = 0;
    top->bready_i = 0;
    top->araddr_i = 0;
    top->arvalid_i = 0;
    top->rready_i = 0;

    for (int i = 0; i < 4; ++i) {{
        tick(top, trace, &time_ps);
    }}

    top->rst_ni = 1;

    for (int i = 0; i < 8; ++i) {{
        tick(top, trace, &time_ps);
    }}

    printf("OpenTSP standalone Verilator top smoke test: PASS\\n");

    trace->close();
    delete trace;
    delete top;
    return 0;
}}
'''


def generate_build_script(build: VerilatorTopBuild) -> str:
    """Generate a POSIX shell script for building the standalone top."""

    source_args = " \\\n  ".join(
        f'"$REPO_ROOT/{source.as_posix()}"' for source in build.sources
    )

    return f'''#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by OpenTSP Edge.
# Build the standalone Verilator simulation for {build.top_module}.

REPO_ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/../.." && pwd)"
cd "$REPO_ROOT"

rm -rf "$REPO_ROOT/{build.obj_dir.as_posix()}"

verilator -cc --exe --build --trace --timing \\
  --top-module {build.top_module} \\
  --Mdir "$REPO_ROOT/{build.obj_dir.as_posix()}" \\
  -o {build.binary_name} \\
  {source_args} \\
  "$REPO_ROOT/{build.main_cpp.as_posix()}"

echo "Built: $REPO_ROOT/{build.obj_dir.as_posix()}/{build.binary_name}"
echo "Run:   $REPO_ROOT/{build.obj_dir.as_posix()}/{build.binary_name}"
'''


def create_verilator_top_build(
    filelist_path: str | Path = DEFAULT_FILELIST,
    output_dir: str | Path = DEFAULT_OUTPUT_DIR,
    top_module: str = DEFAULT_TOP_MODULE,
) -> VerilatorTopBuild:
    """Create the standalone Verilator build bundle."""

    filelist = Path(filelist_path)
    out_dir = Path(output_dir)
    sources = read_filelist(filelist)

    out_dir.mkdir(parents=True, exist_ok=True)

    main_cpp = out_dir / f"{top_module}_main.cpp"
    build_script = out_dir / "build.sh"
    metadata_json = out_dir / "verilator_top_build.json"

    build = VerilatorTopBuild(
        top_module=top_module,
        filelist_path=filelist,
        output_dir=out_dir,
        sources=sources,
        main_cpp=main_cpp,
        build_script=build_script,
        metadata_json=metadata_json,
    )

    main_cpp.write_text(generate_main_cpp(top_module), encoding="utf-8")
    build_script.write_text(generate_build_script(build), encoding="utf-8")

    metadata = {
        "kind": "opentsp.verilator_top_build.v1",
        "top_module": build.top_module,
        "filelist": build.filelist_path.as_posix(),
        "output_dir": build.output_dir.as_posix(),
        "main_cpp": build.main_cpp.as_posix(),
        "build_script": build.build_script.as_posix(),
        "obj_dir": build.obj_dir.as_posix(),
        "binary_name": build.binary_name,
        "sources": [source.as_posix() for source in build.sources],
        "verilator_command": build.verilator_command(),
    }
    metadata_json.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    return build
