from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .hardware_export import export_default_matmul_4x4_hardware_bundle
from .hardware_loader import load_hardware_bundle
from .host_driver import (
    ADDR_C00,
    ADDR_C01,
    ADDR_C10,
    ADDR_C11,
    ADDR_CONTROL,
    ADDR_DATA_ADDR,
    ADDR_DATA_BANK,
    ADDR_DATA_WORD,
    ADDR_INSTR_ADDR,
    ADDR_INSTR_WORD,
    ADDR_PROGRAM_LEN,
    ADDR_STATUS,
    CONTROL_CLEAR,
    CONTROL_START,
    STATUS_DONE,
    STATUS_STORED_VALID,
    HostWrite,
    build_bundle_host_writes,
)


@dataclass(frozen=True)
class CHostExportResult:
    """Paths and counts for a generated C-style host runner."""

    c_path: Path
    h_path: Path
    total_writes: int
    tile_program_count: int


REGISTER_DEFINES = {
    "OPENTSP_REG_CONTROL": ADDR_CONTROL,
    "OPENTSP_REG_STATUS": ADDR_STATUS,
    "OPENTSP_REG_PROGRAM_LEN": ADDR_PROGRAM_LEN,
    "OPENTSP_REG_INSTR_ADDR": ADDR_INSTR_ADDR,
    "OPENTSP_REG_INSTR_WORD": ADDR_INSTR_WORD,
    "OPENTSP_REG_DATA_ADDR": ADDR_DATA_ADDR,
    "OPENTSP_REG_DATA_BANK": ADDR_DATA_BANK,
    "OPENTSP_REG_DATA_WORD": ADDR_DATA_WORD,
    "OPENTSP_REG_C00": ADDR_C00,
    "OPENTSP_REG_C01": ADDR_C01,
    "OPENTSP_REG_C10": ADDR_C10,
    "OPENTSP_REG_C11": ADDR_C11,
}

CONTROL_DEFINES = {
    "OPENTSP_CONTROL_START": CONTROL_START,
    "OPENTSP_CONTROL_CLEAR": CONTROL_CLEAR,
    "OPENTSP_STATUS_DONE": STATUS_DONE,
    "OPENTSP_STATUS_STORED_VALID": STATUS_STORED_VALID,
}


def flatten_bundle_host_writes(bundle_dir: Path) -> tuple[HostWrite, ...]:
    """Load a hardware bundle and return host writes for all tile programs."""

    bundle = load_hardware_bundle(bundle_dir)
    writes_by_tile = build_bundle_host_writes(bundle)
    flattened: list[HostWrite] = []
    for tile in bundle.tile_programs:
        flattened.extend(writes_by_tile[tile.name])
    return tuple(flattened)


def _header_guard(name: str) -> str:
    clean = "".join(ch if ch.isalnum() else "_" for ch in name.upper())
    return f"OPENTSP_{clean}_H"


def render_c_header(*, h_name: str = "opentsp_matmul_4x4_runner.h") -> str:
    """Render a portable C header for the OpenTSP toy host interface."""

    guard = _header_guard(Path(h_name).name)
    lines: list[str] = [
        "/* Auto-generated by OpenTSP. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "typedef struct {",
        "    uint32_t addr;",
        "    uint32_t value;",
        "} opentsp_host_write_t;",
        "",
    ]

    for name, value in REGISTER_DEFINES.items():
        lines.append(f"#define {name:<28} 0x{int(value):02X}u")
    lines.append("")
    for name, value in CONTROL_DEFINES.items():
        lines.append(f"#define {name:<28} 0x{int(value):08X}u")

    lines.extend(
        [
            "",
            "extern const opentsp_host_write_t OPENTSP_MATMUL_4X4_WRITES[];",
            "extern const size_t OPENTSP_MATMUL_4X4_WRITE_COUNT;",
            "extern const int32_t OPENTSP_MATMUL_4X4_EXPECTED_C[4][4];",
            "",
            "void opentsp_run_matmul_4x4(",
            "    void (*write_reg)(uint32_t addr, uint32_t value),",
            "    uint32_t (*read_reg)(uint32_t addr),",
            "    int32_t out_c[4][4]",
            ");",
            "",
            f"#endif /* {guard} */",
            "",
        ]
    )
    return "\n".join(lines)


def _format_write_array(writes: tuple[HostWrite, ...]) -> list[str]:
    rows: list[str] = []
    for idx, write in enumerate(writes):
        comment = f"/* {idx:03d} {write.name} {write.description} */"
        rows.append(f"    {{0x{write.addr:02X}u, 0x{write.value:08X}u}}, {comment}")
    return rows


def render_c_runner(
    writes: tuple[HostWrite, ...],
    *,
    expected_c: tuple[tuple[int, ...], ...],
    h_name: str = "opentsp_matmul_4x4_runner.h",
) -> str:
    """Render a C source file with host writes and a tiny polling runner."""

    lines: list[str] = [
        "/* Auto-generated by OpenTSP. */",
        f'#include "{h_name}"',
        "",
        "const opentsp_host_write_t OPENTSP_MATMUL_4X4_WRITES[] = {",
        *_format_write_array(writes),
        "};",
        "",
        "const size_t OPENTSP_MATMUL_4X4_WRITE_COUNT = sizeof(OPENTSP_MATMUL_4X4_WRITES) / sizeof(OPENTSP_MATMUL_4X4_WRITES[0]);",
        "",
        "const int32_t OPENTSP_MATMUL_4X4_EXPECTED_C[4][4] = {",
    ]
    for row in expected_c:
        values = ", ".join(str(int(v)) for v in row)
        lines.append(f"    {{{values}}},")
    lines.extend(
        [
            "};",
            "",
            "static int32_t opentsp_i32(uint32_t value) {",
            "    return (int32_t)value;",
            "}",
            "",
            "void opentsp_run_matmul_4x4(",
            "    void (*write_reg)(uint32_t addr, uint32_t value),",
            "    uint32_t (*read_reg)(uint32_t addr),",
            "    int32_t out_c[4][4]",
            ") {",
            "    size_t tile = 0;",
            "    size_t i = 0;",
            "    while (i < OPENTSP_MATMUL_4X4_WRITE_COUNT) {",
            "        write_reg(OPENTSP_MATMUL_4X4_WRITES[i].addr, OPENTSP_MATMUL_4X4_WRITES[i].value);",
            "        if (OPENTSP_MATMUL_4X4_WRITES[i].addr == OPENTSP_REG_CONTROL &&",
            "            OPENTSP_MATMUL_4X4_WRITES[i].value == OPENTSP_CONTROL_START) {",
            "            uint32_t status = 0;",
            "            do {",
            "                status = read_reg(OPENTSP_REG_STATUS);",
            "            } while ((status & OPENTSP_STATUS_DONE) == 0u);",
            "",
            "            if ((status & OPENTSP_STATUS_STORED_VALID) != 0u) {",
            "                int row = (tile >= 2) ? 2 : 0;",
            "                int col = (tile % 2) ? 2 : 0;",
            "                out_c[row + 0][col + 0] = opentsp_i32(read_reg(OPENTSP_REG_C00));",
            "                out_c[row + 0][col + 1] = opentsp_i32(read_reg(OPENTSP_REG_C01));",
            "                out_c[row + 1][col + 0] = opentsp_i32(read_reg(OPENTSP_REG_C10));",
            "                out_c[row + 1][col + 1] = opentsp_i32(read_reg(OPENTSP_REG_C11));",
            "            }",
            "            tile += 1;",
            "        }",
            "        i += 1;",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def export_c_host_runner(bundle_dir: Path, out_dir: Path) -> CHostExportResult:
    """Export a C-style host runner from a hardware bundle."""

    bundle = load_hardware_bundle(bundle_dir)
    writes = flatten_bundle_host_writes(bundle_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    h_path = out_dir / "opentsp_matmul_4x4_runner.h"
    c_path = out_dir / "opentsp_matmul_4x4_runner.c"
    h_path.write_text(render_c_header(h_name=h_path.name), encoding="utf-8")
    c_path.write_text(render_c_runner(writes, expected_c=bundle.expected_c, h_name=h_path.name), encoding="utf-8")

    return CHostExportResult(
        c_path=c_path,
        h_path=h_path,
        total_writes=len(writes),
        tile_program_count=len(bundle.tile_programs),
    )


def export_default_c_host_runner(out_dir: Path) -> CHostExportResult:
    """Create the default 4x4 hardware bundle and export a C host runner for it."""

    bundle_dir = out_dir.parent / "hardware_bundle" / "matmul_4x4"
    export_default_matmul_4x4_hardware_bundle(bundle_dir)
    return export_c_host_runner(bundle_dir, out_dir)
