from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .c_host_runner import CHostExportResult, export_default_c_host_runner


@dataclass(frozen=True)
class CppHostExportResult:
    """Paths and counts for a generated C++ host executable scaffold."""

    c_path: Path
    h_path: Path
    cpp_path: Path
    makefile_path: Path
    total_writes: int
    tile_program_count: int


CPP_HOST_SIM = r"""/* Auto-generated by OpenTSP. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "opentsp_matmul_4x4_runner.h"

static uint32_t g_instr_mem[64];
static uint32_t g_a_mem[64];
static uint32_t g_b_mem[64];
static uint32_t g_instr_addr;
static uint32_t g_data_addr;
static uint32_t g_data_bank;
static uint32_t g_program_len;
static uint32_t g_status;
static uint32_t g_c00;
static uint32_t g_c01;
static uint32_t g_c10;
static uint32_t g_c11;

static int8_t lane_i8(uint32_t word, int shift) {
    return (int8_t)((word >> shift) & 0xFFu);
}

static uint32_t i32_to_u32(int32_t value) {
    return (uint32_t)value;
}

static void clear_model(void) {
    memset(g_instr_mem, 0, sizeof(g_instr_mem));
    memset(g_a_mem, 0, sizeof(g_a_mem));
    memset(g_b_mem, 0, sizeof(g_b_mem));
    g_instr_addr = 0;
    g_data_addr = 0;
    g_data_bank = 0;
    g_program_len = 0;
    g_status = 0;
    g_c00 = 0;
    g_c01 = 0;
    g_c10 = 0;
    g_c11 = 0;
}

static void execute_model(void) {
    int8_t a00 = 0, a01 = 0, a10 = 0, a11 = 0;
    int8_t b00 = 0, b01 = 0, b10 = 0, b11 = 0;
    int32_t c00 = 0, c01 = 0, c10 = 0, c11 = 0;

    g_status = 1u; /* busy */

    for (uint32_t pc = 0; pc < g_program_len && pc < 64u; ++pc) {
        uint32_t instr = g_instr_mem[pc];
        uint32_t opcode = instr & 0xFFu;

        if (opcode == 1u) { /* LOAD_A */
            uint32_t word = g_a_mem[pc];
            a00 = lane_i8(word, 0);
            a01 = lane_i8(word, 8);
            a10 = lane_i8(word, 16);
            a11 = lane_i8(word, 24);
        } else if (opcode == 2u) { /* LOAD_B */
            uint32_t word = g_b_mem[pc];
            b00 = lane_i8(word, 0);
            b01 = lane_i8(word, 8);
            b10 = lane_i8(word, 16);
            b11 = lane_i8(word, 24);
        } else if (opcode == 3u) { /* MAC_TILE */
            c00 += (int32_t)a00 * (int32_t)b00 + (int32_t)a01 * (int32_t)b10;
            c01 += (int32_t)a00 * (int32_t)b01 + (int32_t)a01 * (int32_t)b11;
            c10 += (int32_t)a10 * (int32_t)b00 + (int32_t)a11 * (int32_t)b10;
            c11 += (int32_t)a10 * (int32_t)b01 + (int32_t)a11 * (int32_t)b11;
        } else if (opcode == 4u) { /* STORE_C */
            g_c00 = i32_to_u32(c00);
            g_c01 = i32_to_u32(c01);
            g_c10 = i32_to_u32(c10);
            g_c11 = i32_to_u32(c11);
        }
    }

    g_status = OPENTSP_STATUS_DONE | OPENTSP_STATUS_STORED_VALID;
}

static void host_write_reg(uint32_t addr, uint32_t value) {
    if (addr == OPENTSP_REG_CONTROL) {
        if ((value & OPENTSP_CONTROL_CLEAR) != 0u) {
            clear_model();
        }
        if ((value & OPENTSP_CONTROL_START) != 0u) {
            execute_model();
        }
    } else if (addr == OPENTSP_REG_PROGRAM_LEN) {
        g_program_len = value;
    } else if (addr == OPENTSP_REG_INSTR_ADDR) {
        g_instr_addr = value & 63u;
    } else if (addr == OPENTSP_REG_INSTR_WORD) {
        g_instr_mem[g_instr_addr] = value;
    } else if (addr == OPENTSP_REG_DATA_ADDR) {
        g_data_addr = value & 63u;
    } else if (addr == OPENTSP_REG_DATA_BANK) {
        g_data_bank = value & 1u;
    } else if (addr == OPENTSP_REG_DATA_WORD) {
        if (g_data_bank == 0u) {
            g_a_mem[g_data_addr] = value;
        } else {
            g_b_mem[g_data_addr] = value;
        }
    }
}

static uint32_t host_read_reg(uint32_t addr) {
    if (addr == OPENTSP_REG_STATUS) {
        return g_status;
    }
    if (addr == OPENTSP_REG_C00) {
        return g_c00;
    }
    if (addr == OPENTSP_REG_C01) {
        return g_c01;
    }
    if (addr == OPENTSP_REG_C10) {
        return g_c10;
    }
    if (addr == OPENTSP_REG_C11) {
        return g_c11;
    }
    return 0u;
}

int main(void) {
    int32_t out_c[4][4];
    memset(out_c, 0, sizeof(out_c));
    clear_model();

    opentsp_run_matmul_4x4(host_write_reg, host_read_reg, out_c);

    for (int r = 0; r < 4; ++r) {
        for (int c = 0; c < 4; ++c) {
            if (out_c[r][c] != OPENTSP_MATMUL_4X4_EXPECTED_C[r][c]) {
                fprintf(stderr, "Mismatch at C[%d][%d]: got %d expected %d\n", r, c, out_c[r][c], OPENTSP_MATMUL_4X4_EXPECTED_C[r][c]);
                return 1;
            }
        }
    }

    printf("OpenTSP C++ host simulation: PASS\n");
    return 0;
}
"""

MAKEFILE_TEXT = """CXX ?= g++
CXXFLAGS ?= -std=c++17 -O2 -Wall -Wextra

TARGET := opentsp_matmul_4x4_host_sim
SOURCES := opentsp_matmul_4x4_runner.c opentsp_matmul_4x4_host_sim.cpp

.PHONY: all run clean

all: $(TARGET)

$(TARGET): $(SOURCES) opentsp_matmul_4x4_runner.h
	$(CXX) $(CXXFLAGS) $(SOURCES) -o $(TARGET)

run: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(TARGET)
"""


def render_cpp_host_sim() -> str:
    """Render a standalone C++ register-model host executable."""

    return CPP_HOST_SIM


def render_cpp_host_makefile() -> str:
    """Render a tiny Makefile for the generated C++ host executable."""

    return MAKEFILE_TEXT


def export_cpp_host_runner(out_dir: Path, *, c_host_result: CHostExportResult | None = None) -> CppHostExportResult:
    """Export generated C runner files plus a C++ host executable scaffold."""

    out_dir.mkdir(parents=True, exist_ok=True)
    if c_host_result is None:
        c_host_result = export_default_c_host_runner(out_dir)

    cpp_path = out_dir / "opentsp_matmul_4x4_host_sim.cpp"
    makefile_path = out_dir / "Makefile"
    cpp_path.write_text(render_cpp_host_sim(), encoding="utf-8")
    makefile_path.write_text(render_cpp_host_makefile(), encoding="utf-8")

    return CppHostExportResult(
        c_path=c_host_result.c_path,
        h_path=c_host_result.h_path,
        cpp_path=cpp_path,
        makefile_path=makefile_path,
        total_writes=c_host_result.total_writes,
        tile_program_count=c_host_result.tile_program_count,
    )


def export_default_cpp_host_runner(out_dir: Path) -> CppHostExportResult:
    """Create the default C runner and C++ host executable scaffold."""

    return export_cpp_host_runner(out_dir)
